### ISSUE TITLE
gliched image / crash with larger meshes

### ISSUE THREAD

**Issue by ProgrammierPatrick** [WilliamLewww/vulkan_ray_tracing_minimal_abstraction#1]
Hi, first thanks for this repo, it is very helpful to have code to look at for this new vulkan raytracing stuff!

I experimented with replacing the cube_scene.obj with my own test meshes and it looks like meshes larger than ~100verts have  problems. For testing, I modified the cube_scene .obj to have meshes with varying amounts of geometry for testing:
- `cube_scene_pile.obj`: 306 triangles, 220 vertices
- `cube_scene_large_pile.obj`: 1482 triangles, 1004 vertices
- `cube_scene_larger_pile.obj`: 9798 triangles, 6548 vertices
for comparison, the old `cube_scene.obj` only has 42 triangles and 44 vertices.

Both `cube_scene_pile.obj` and `cube_scene_large_pile.obj` produce visual glitches when loading (see below).

With the largest mesh, however, the application crashes in `createBottomLevelAccelerationStructure()` at `vkQueueWaitIdle()` with `VK_ERROR_DEVICE_LOST`.

system information:
- Intel Core i7-9750H
- GeForce RTX 2070 Max-Q (nvidia driver: 460.32.03)
- x64 LInux 5.10.7 (Manjaro, testing branch)

Any idea why this happens or what to do to fix it? I suspect it has something to do with the bottom level acceleration structure, because my application always crashes with `VK_ERROR_DEVICE_LOST` when I try to build ASs of this size.

My fork containing these meshes and some slight code modifications to check vulkan return values:
[https://github.com/ProgrammierPatrick/vulkan_ray_tracing_minimal_abstraction](https://github.com/ProgrammierPatrick/vulkan_ray_tracing_minimal_abstraction)

visual glitches: (maybe hard to see)

cube_scene_pile.obj:
![cube_scene_pile](https://user-images.githubusercontent.com/26128352/104827006-c8da1080-5859-11eb-91b8-fab6b62aa61c.jpg)

cube_scene_large_pile.obj
![cube_scene_large_pile](https://user-images.githubusercontent.com/26128352/104827013-d68f9600-5859-11eb-9b23-b07b9cb1b749.jpg)

My modified objs:

![cube_scene_pile mesh](https://user-images.githubusercontent.com/26128352/104825162-89f78b00-5858-11eb-8e85-822cc51d5c04.jpg)
![cube_scene_large_pile mesh](https://user-images.githubusercontent.com/26128352/104825165-8f54d580-5858-11eb-91d8-90f03ddb8775.jpg)
![cube_scene_larger_pile mesh](https://user-images.githubusercontent.com/26128352/104825167-911e9900-5858-11eb-84a1-aa2c41260e0c.jpg)

**Comment by WilliamLewww** [comment]
Hey, I am glad I am able to help you get a head start with ray tracing!

For the first two models, the issue stems with my poorly coded fragment shader. In this case I hardcoded the primitive indices for light sources (primitive #40 and primitive #41).

Line 70 in basic.frag:
`if (gl_PrimitiveID == 40 || gl_PrimitiveID == 41) {`

I was able to fix this problem in one of my other projects by storing the number of light primitives and the index of each light primitive in a buffer. Here is the structure that I created in my other project to store light information:

```
layout(binding = 6, set = 1) buffer MaterialLightBuffer { 
  uint count;                           // # of light primitives
  uint indicesPrimitive[64];     // each item contains a primitive index.
} materialLightBuffer;

i.e.
materialLightBuffer.count == 2;
materialLightBuffer.indicesPrimitive[0] == 40;
materialLightBuffer.indicesPrimitive[1] == 41;
materialLightBuffer.indicesPrimitive[2] == -1;
```

When I trash most of the fragment shader code and just output the normal of the rasterized primitive, I get the following images:

![b](https://user-images.githubusercontent.com/14305903/104831697-1ba6ce80-5840-11eb-9482-bd1dd0eff1c3.png)

![a](https://user-images.githubusercontent.com/14305903/104831689-1184d000-5840-11eb-8a01-a40db0a2d34b.png)

I am still currently searching for the issue with the `cube_scene_larger_pile.obj` model, but I think it might have to do something with allocating the right amount of memory in the scratch buffer.

Let me know if you are still running into issues or if my explanation doesn't make too much sense. I'll create a new comment when I am able to solve the issue with the largest pile model.

**Comment by ProgrammierPatrick** [comment]
Thanks for the explanation of the hard coded lighting, that does make a lot of sense.

For the `cube_scene_larger_pile.obj`, I may have found the bug. In the call to `pvkGetAccelerationStructureBuildSizesKHR` the 4th argument `pMaxPrimitiveCounts` gets a pointer to `accelerationStructureBuildGeometryInfo.geometryCount` (with value 1). I was comparing the code with the source code of the Quake 2 RTX vulkan implementation and noticed that they put a pointer to the maximum number of primitives there:
[https://github.com/NVIDIA/Q2RTX/blob/514b136acacd217a003bcb3815f32416028ea591/src/refresh/vkpt/path_tracer.c#L495](https://github.com/NVIDIA/Q2RTX/blob/514b136acacd217a003bcb3815f32416028ea591/src/refresh/vkpt/path_tracer.c#L495)
```c
// Find size to build on the device
uint32_t max_primitive_count = max(num_vertices, num_indices) / 3; // number of tris
VkAccelerationStructureBuildSizesInfoKHR sizeInfo = { .sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR };
qvkGetAccelerationStructureBuildSizesKHR(qvk.device, VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR, &buildInfo, &max_primitive_count, &sizeInfo);
```

From the Vulkan documentation:  
> `pMaxPrimitiveCounts` is a pointer to an array of `pBuildInfo->geometryCount` `uint32_t` values defining the number of primitives built into each geometry.

When I change the code to the following, it seems to work. I am not sure why they are doing the max though.
```c
  uint32_t max_primitive_count = scene->attributes.num_face_num_verts;
  pvkGetAccelerationStructureBuildSizesKHR(app->logicalDevice, 
                                           VK_ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_KHR, 
                                           &accelerationStructureBuildGeometryInfo, 
                                           &max_primitive_count,  // before: &accelerationStructureBuildGeometryInfo.geometryCount, 
                                           &accelerationStructureBuildSizesInfo);
```

Also, i noticed they do `.maxVertex = scene->attributes.num_vertices - 1` instead of `scene->attributes.num_vertices` in the `VkAccelerationStructureGeometryTrianglesDataKHR`. This could also be a bug in this repo.

**Comment by WilliamLewww** [comment]
Closed from rework.
