### ISSUE TITLE
[Core Dump] Vulkan API exception: return code -6 (vkCreateInstance)

### ISSUE THREAD

**Issue by DashCruft** [WilliamLewww/vulkan_ray_tracing_minimal_abstraction#11]
After compiling vulkan_ray_tracing_minimal_abstraction/ray_pipeline and running the app via ./application, I get this error:

![image](https://user-images.githubusercontent.com/59381835/166616412-bc34a080-5b94-4bd1-bbe7-c95c6259d2c1.png)

Output of `vulkaninfo | grep KHR_ray`:
![image](https://user-images.githubusercontent.com/59381835/166616446-570a0d4b-d6f8-4182-9352-a8a66a5fabb2.png)

Is there something I'm missing?

**Comment by WilliamLewww** [comment]
Oh, I see it's `return code -6` (VK_ERROR_LAYER_NOT_PRESENT).

The example uses the Khronos validation layer (VkLayer_khronos_validation.json) from Vulkan-ValidationLayers.

You might need to set VK_LAYER_PATH to the directory containing the layer (i.e. export VK_LAYER_PATH="DIRECTORY_GOES_HERE/share/vulkan/explicit_layer.d".

If you are using the VulkanSDK, I think there is a file you can source to set the correct paths.

**Comment by DashCruft** [comment]
Just tried exporting it (`export VK_LAYER_PATH="/usr/share/vulkan/explicit_layer.d"`)

The error unfortunately still occurs

**Comment by WilliamLewww** [comment]
Hmm that's a little strange, it should be working after properly locating the VkLayer_khronos_validation layer.

I think it still not locating the validation layer properly.
My output:
```
Validation Information: [ UNASSIGNED-khronos-validation-createinstance-status-message ] Object 0: handle = 0x5643dcb2fd50, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xd7fa5f44 | Khronos Validation Layer Active:
    Settings File: None. Default location is /storage/projects/vulkan_ray_tracing_minimal_abstraction/ray_pipeline/build\vk_layer_settings.txt.
    Current Enables: VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT, VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION.
    Current Disables: None.

Validation Performance Warning: [ UNASSIGNED-khronos-Validation-debug-build-warning-message ] Object 0: handle = 0x5643dcb2fd50, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x26ac7233 | VALIDATION LAYERS WARNING: Using debug builds of the validation layers *will* adversely affect performance.
AMD RADV NAVY_FLOUNDER
```

I create the following branch that removes validation: https://github.com/WilliamLewww/vulkan_ray_tracing_minimal_abstraction/tree/no-validation

I think this should probably work because it removes the use of the Khronos validation layer, but I would highly recommend trying to fix the validation layer because it is very useful for debugging Vulkan issues.

**Comment by DashCruft** [comment]
Just tried it. 

This time, I get the following error:
```
AMD RADV DIMGREY_CAVEFISH
terminate called after throwing an instance of 'std::runtime_error'
  what():  Vulkan API exception: return code -7 (vkCreateDevice)
zsh: IOT instruction (core dumped)  ./application
```

🤔

**Comment by WilliamLewww** [comment]
Could you check to see if you have all of the following device extensions:

```
std::vector<const char *> deviceExtensionList = {
      "VK_KHR_ray_tracing_pipeline",
      "VK_KHR_acceleration_structure",
      "VK_EXT_descriptor_indexing",
      "VK_KHR_maintenance3",
      "VK_KHR_buffer_device_address",
      "VK_KHR_deferred_host_operations",
      "VK_KHR_swapchain"};
```

**Comment by DashCruft** [comment]
I tried doing it with proprietary driver instead. It seems to be working. 

However, there is a big chunk of black in the bottom. The camera moves fine with cursor tho

![image](https://user-images.githubusercontent.com/59381835/167061329-d4a42d8f-47c0-420a-b621-e15c38191695.png)

**Comment by DashCruft** [comment]
Nevermind. Just had to hit space and move a bit. The camera is completely fine now!

![image](https://user-images.githubusercontent.com/59381835/167061621-a47e4fb4-9e1f-418a-970c-ae0accffa1a8.png)

**Comment by WilliamLewww** [comment]
Glad to hear it's working now!

**Comment by DashCruft** [comment]
Thanks for your patience and help!
