### ISSUE TITLE
can't compile latest windows and visual studio

### ISSUE THREAD

**Issue by cchriste** [WilliamLewww/vulkan_ray_tracing_minimal_abstraction#6]
I get errors from initialization of empty braces to implicit conversion of longs for printf. 

Anything I happen to be missing? I'm excited to look at this project.

Thanks!

**Comment by WilliamLewww** [comment]
Oh I haven't tried building on windows and the issue might be from using different compilers. Its working with GCC 11 but I think windows uses vc++. Do you have line numbers for the errors you are getting?

**Comment by cchriste** [comment]
Thanks for the info. I'm not sure what magic is necessary to compile on Windows. I've tried manually changing a few things, but no luck so far. Here is some output:
```
Build started...
1>------ Build started: Project: copy_resources, Configuration: Debug x64 ------
2>------ Build started: Project: application, Configuration: Debug x64 ------
2>main.c
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(161,42): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(168,12): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'VkDeviceSize'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(168,12): message : consider using '%lld' in the format string
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(168,12): message : consider using '%Id' in the format string
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(168,12): message : consider using '%I64d' in the format string
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(174,46): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(195,53): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(204,54): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(209,30): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(214,30): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(226,40): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(248,46): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(286,24): warning C4090: 'function': different 'const' qualifiers
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(290,40): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(298,46): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(310,63): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(329,20): warning C4090: 'function': different 'const' qualifiers
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(344,22): warning C4090: 'function': different 'const' qualifiers
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(459,42): error C2059: syntax error: '}'
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(478,35): warning C4090: 'function': different 'const' qualifiers
2>C:\code\vulkan\vulkan_ray_tracing_minimal_abstraction\ray_pipeline\src\main.c(506,51): error C2059: syntax error: '}'
```

**Comment by WilliamLewww** [comment]
Ahhh, it looks like the compiler doesn't like the initialization of an empty struct:
https://github.com/WilliamLewww/vulkan_ray_tracing_minimal_abstraction/blob/4fd5a60de85425b6c0b5704d4abe3b72fa334f71/ray_pipeline/src/main.c#L161

Here are some options you could try to fix the error:
1. Initialize the struct with data (delete lines 162-165)
```
VkBufferCreateInfo bufferCreateInfo = {
  .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
  .size = size,
  .usage = usageFlags,
  .sharingMode = VK_SHARING_MODE_EXCLUSIVE
};
```
2. Don't initialize an empty struct
```
VkBufferCreateInfo bufferCreateInfo;
```
3. Initialize empty struct by casting?
```
VkBufferCreateInfo bufferCreateInfo = (VkBufferCreateInfo){}; 
```

I'm not too sure how the windows C compiler would handle these changes, but could you try these options?

**Comment by cchriste** [comment]
I was able to get it to compile by starting with an empty Vulkan project (added to Visual Studio by the Vulkan installation on Windows), then porting the code from this project, and finally making a few changes that simply wouldn't compile. These include both a few relatively minor modifications of the code (ex: casting a void pointer for assignment), as well as some modifications to the project settings. I can try to share these separately at a later date (it's trickier than simply a git diff, but not impossible--I'm just unclear on why the new project compiles and this one doesn't and I've been trying to make it work for some time now). 

So, after a quiet moment of celebration, I tried to run it. And it immediately threw an exception trying to get a device queue while creating a logical connection. A shiny new issue! 

I will try to wrestle a Windows build into this before I start submitting such issues, but... I'll probably try to fix them first. My apologies if it feels like abandonment, but my primary motivation for cloning this particular repo was to see the explicit difference between the ray tracing pipeline versus direct use of a shader in order to better understand these two methods of using Vulkan (as well as Vulkan itself). Recommendations for learning this would be welcome, as well as your opinion on whether it's worth spending the time to submit a fix for the compilation of this repo using Windows. Thanks again!

**Comment by WilliamLewww** [comment]
No worries! This project was made specifically for the purpose of helping individuals learn ray tracing through Vulkan; I wanted this to work more as a `Hello World` application which should be abandoned once the individual has ray tracing under control.

I think going the route of working with a super basic Vulkan application that runs and converting it to use ray-tracing might be a little more useful for you. Going that route, you can add ray tracing step by step while compiling on the way to see if all the components work. I think it might be easier to try to implement the ray query method first just because it uses the graphics pipeline which should already be implemented in a basic Vulkan application. If you get stuck on an error or need a place to start, feel free to use this issue more as a public chatroom and I'll be glad to help you through ray tracing!

**Comment by WilliamLewww** [comment]
Closed from rework.
